#!/usr/bin/env bash
# ============================================================================
# run-live-tests.sh — Live-QA Evidence Script (Python/Playwright)
# ============================================================================
# Startet das echte GPU-Dashboard, führt Playwright-Browser-Tests aus und
# sammelt Screenshots, HTML-Dumps und Logs als Beweisartefakte.
#
# KEIN Mock: Der echte dashboard/server.py wird via pytest-Fixture gestartet.
# ============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
ARTIFACTS="$ROOT/qa/live/artifacts"
REPORT="$ROOT/qa/live/latest-live-test-report.md"
TIMESTAMP="$(date -Iseconds)"

# --- Ordner ----------------------------------------------------------------
mkdir -p "$ARTIFACTS/screenshots"
mkdir -p "$ARTIFACTS/videos"
mkdir -p "$ARTIFACTS/traces"
mkdir -p "$ARTIFACTS/html-report"
mkdir -p "$ARTIFACTS/logs"

# --- Report-Header ---------------------------------------------------------
cat > "$REPORT" <<EOF
# Live-QA Test Report

**Datum:** $TIMESTAMP
**Commit:** $(git -C "$ROOT" rev-parse --short HEAD)
**Branch:** $(git -C "$ROOT" branch --show-current)

## Test-Stack
- **Test-Framework:** pytest + Playwright (Python sync_api)
- **Browser:** Chromium (headless)
- **Echte App:** dashboard/server.py (wird von pytest-Fixture gestartet)
- **App-URL:** http://127.0.0.1:8889
- **Mock-Status:** KEIN Mock — echter HTTP-Server, echter Browser

---

EOF

# --- Playwright-Tests ausführen ---------------------------------------------
echo "## Running Playwright Live Tests" | tee -a "$REPORT"
echo "" | tee -a "$REPORT"

cd "$ROOT"
python3 -m pytest tests/playwright/ \
    -v \
    --tb=long \
    --timeout=30 \
    2>&1 | tee "$ARTIFACTS/logs/live-test.log"

STATUS=${PIPESTATUS[0]}

echo "" | tee -a "$REPORT"

# --- Screenshots kopieren ---------------------------------------------------
echo "## Collecting Screenshot Evidence" | tee -a "$REPORT"
echo "" | tee -a "$REPORT"

# Vom Dashboard-Browser-Test
if [ -d "tests/playwright/screenshots/baseline" ]; then
    cp tests/playwright/screenshots/baseline/*.png "$ARTIFACTS/screenshots/" 2>/dev/null || true
    cp tests/playwright/screenshots/baseline/*.html "$ARTIFACTS/screenshots/" 2>/dev/null || true
fi

# Von der visuellen Regression
if [ -f "tests/playwright/baselines/dashboard_visual_regression.png" ]; then
    cp tests/playwright/baselines/dashboard_visual_regression.png \
       "$ARTIFACTS/screenshots/00-visual-regression-baseline.png" 2>/dev/null || true
fi

# Diffs (falls vorhanden)
if ls tests/playwright/screenshots/diff/*.png 2>/dev/null; then
    cp tests/playwright/screenshots/diff/*.png "$ARTIFACTS/screenshots/" 2>/dev/null || true
fi

# --- Ergebnis ---------------------------------------------------------------
echo "## Result" | tee -a "$REPORT"
echo "" | tee -a "$REPORT"

if [ "$STATUS" -eq 0 ]; then
    echo "**Status: PASS** :white_check_mark:" | tee -a "$REPORT"
else
    echo "**Status: FAIL** :x:" | tee -a "$REPORT"
fi

echo "" | tee -a "$REPORT"

# --- Getestete Flows --------------------------------------------------------
echo "## Tested Flows" | tee -a "$REPORT"
echo "" | tee -a "$REPORT"
echo "| Flow | Viewport | Ergebnis | Screenshot |" | tee -a "$REPORT"
echo "|---|---|---|---|" | tee -a "$REPORT"

# Parse test results from log
while IFS= read -r line; do
    if echo "$line" | grep -q "PASSED"; then
        test_name=$(echo "$line" | sed 's/.*::\(.*\) PASSED.*/\1/')
        echo "| $test_name | Desktop (1280x720) | PASS | — |" | tee -a "$REPORT"
    elif echo "$line" | grep -q "FAILED"; then
        test_name=$(echo "$line" | sed 's/.*::\(.*\) FAILED.*/\1/')
        echo "| $test_name | Desktop (1280x720) | FAIL | — |" | tee -a "$REPORT"
    fi
done < <(grep -E "PASSED|FAILED" "$ARTIFACTS/logs/live-test.log" 2>/dev/null || true)

echo "" | tee -a "$REPORT"

# --- Artifakte auflisten ----------------------------------------------------
echo "## Evidence Artifacts" | tee -a "$REPORT"
echo "" | tee -a "$REPORT"
echo "- **Markdown Report:** qa/live/latest-live-test-report.md" | tee -a "$REPORT"

echo "### Screenshots" | tee -a "$REPORT"
if ls "$ARTIFACTS/screenshots/"*.png 2>/dev/null; then
    find "$ARTIFACTS/screenshots" -type f -name "*.png" | sort | while read -r f; do
        echo "- \`$(basename "$f")\` ($(du -h "$f" | cut -f1))" | tee -a "$REPORT"
    done
else
    echo "- *Keine Screenshots vorhanden*" | tee -a "$REPORT"
fi

echo "" | tee -a "$REPORT"
echo "- **HTML Report:** qa/live/artifacts/html-report/" | tee -a "$REPORT"
echo "- **Logs:** qa/live/artifacts/logs/live-test.log" | tee -a "$REPORT"
echo "- **Traces:** qa/live/artifacts/traces/" | tee -a "$REPORT"

echo "" | tee -a "$REPORT"
echo "---" | tee -a "$REPORT"
echo "*Generated by qa/scripts/run-live-tests.sh — $(date -Iseconds)*" | tee -a "$REPORT"

exit "$STATUS"
